config/routes.rb
Rails.application.routes.draw do
  resources :cryptos
  devise_for :users
  root 'home#index'
  get 'home/about'
  get 'home/lookup'
  # post 'home/lookup' => 'home#lookup_do'
  post 'home/lookup' => 'home#lookup'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/crypto.rb
class Crypto < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cryptos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cryptos_controller.rb
# frozen_string_literal: true

require './lib/coinmarketcap'

# Everything related to the users's coin portfolio.
class CryptosController < ApplicationController
  before_action :set_crypto, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :correct_user, only: %i[ show edit update destroy ]

  # GET /cryptos or /cryptos.json
  def index
    @portfolio_coins = Crypto.where(user: current_user)
    @portfolio_list = Coinmarketcap::CoinInfo.obtain_coin_info @portfolio_coins
    puts @portfolio_list
  end

  # GET /cryptos/1 or /cryptos/1.json
  def show; end

  # GET /cryptos/new
  def new
    @crypto = Crypto.new
  end

  # GET /cryptos/1/edit
  def edit; end

  # POST /cryptos or /cryptos.json
  def create
    @crypto = Crypto.new(crypto_params)
    @crypto.user = current_user

    respond_to do |format|
      if @crypto.save
        format.html { redirect_to @crypto, notice: "Crypto was successfully created." }
        format.json { render :show, status: :created, location: @crypto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cryptos/1 or /cryptos/1.json
  def update
    respond_to do |format|
      if @crypto.update(crypto_params)
        format.html { redirect_to @crypto, notice: "Crypto was successfully updated." }
        format.json { render :show, status: :ok, location: @crypto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @crypto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cryptos/1 or /cryptos/1.json
  def destroy
    @crypto.destroy!

    respond_to do |format|
      format.html { redirect_to cryptos_path, status: :see_other, notice: "Crypto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

private
  def set_crypto
    @crypto = Crypto.find(params[:id])
  end

  def crypto_params
    params.require(:crypto).permit(:symbol, :user_id_id, :cost_per, :amount_owned)
  end

  # Only allow to users see their own coins.
  def correct_user
    @correct = current_user.cryptos.find_by(id: params[:id])
    redirect_to cryptos_url, notice: 'Not allowed' if @correct.nil?
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

require './lib/coinmarketcap'

# Main controller of the website.
class HomeController < ApplicationController
  def index
    @coins = Coinmarketcap::CoinInfo.cached_list
    @my_coins = %w[BTC XRP ADA XLM STEEM]
  end

  def about; end

  def lookup
    if params[:sym].nil? || params[:sym].empty?
      @symbol = 'Hey, you forget to enter a currency'
      return
    end

    @symbol = params[:sym].upcase

    Coinmarketcap::CoinInfo.cached_list.each do |coin|
      @info = coin if coin['symbol'] == @symbol
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cryptos_helper.rb
module CryptosHelper

  def coin_title(symbol, name)
    if symbol != name
      "#{symbol} (#{name})"
    else
      symbol
    end
  end

  def calculate_profit(price, price_buy, amount)
    (price * amount) - (price_buy * amount)
  end

  def portfolio_profit(portfolio_list)
    portfolio_list.reduce(0) do |total, u|
      total + (u[:price].to_d * u[:amount_owned]) - (u[:cost_per] * u[:amount_owned])
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/cryptos/_crypto.html.erb
<div id="<%= dom_id crypto %>">
  <p>
    <strong>Symbol:</strong>
    <%= crypto.symbol %>
  </p>

  <p>
    <strong>Cost per:</strong>
    <%= crypto.cost_per %>
  </p>

  <p>
    <strong>Amount owned:</strong>
    <%= crypto.amount_owned %>
  </p>

</div>

app/views/cryptos/_form.html.erb
<%= form_with(model: crypto) do |form| %>
  <% if crypto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(crypto.errors.count, "error") %> prohibited this crypto from being saved:</h2>

      <ul>
        <% crypto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :symbol, style: "display: block" %>
    <%= form.text_field :symbol %>
  </div>

  <div>
    <%= form.label :cost_per, style: "display: block" %>
    <%= form.text_field :cost_per %>
  </div>

  <div>
    <%= form.label :amount_owned, style: "display: block" %>
    <%= form.text_field :amount_owned %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/cryptos/edit.html.erb
<h1>Editing crypto</h1>

<%= render "form", crypto: @crypto %>

<br>

<div>
  <%= link_to "Show this crypto", @crypto %> |
  <%= link_to "Back to cryptos", cryptos_path %>
</div>

app/views/cryptos/index.html.erb
<h3 class="mb-5">Portfolio Listing</h3>

<div class="float-end pb-2">
  <%= link_to "Add coin", new_crypto_path, class: 'btn btn-outline-secondary' %>
</div>

<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th scope="col">Coin</th>
      <th scope="col">Current Price</th>

      <th scope="col">1h %</th>
      <th scope="col">21h %</th>
      <th scope="col">7d %</th>

      <th scope="col">Total Value</th>
      <th scope="col">Profit/Loss</th>
      <th scope="col">Buy Price</th>
      <th scope="col">Amount</th>
    </tr>
  </thead>
  <tbody>
  <% @portfolio_list.each do |c| %>
    <tr>
      <td><%= link_to coin_title(c[:symbol], c[:name]), crypto_path(c[:id]) %></td>
      <td>$ <%= c[:price].round(4) %></td>

      <td><%= (c[:percent_change_1h] * 100).round(2) %></td>
      <td><%= (c[:percent_change_24h] * 100).round(2) %></td>
      <td><%= (c[:percent_change_7d] * 100).round(2) %></td>

      <td>$ <%= (c[:price].to_d * c[:amount_owned]).round(2) %></td>
      <td>$ <%= calculate_profit(c[:price].to_d, c[:cost_per], c[:amount_owned]).round(2) %></td>
      <td><%= c[:cost_per] %></td>
      <td><%= c[:amount_owned] %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<strong>Portfolio Profit/Loss: </strong><%= number_to_currency(portfolio_profit(@portfolio_list)) %>

app/views/cryptos/new.html.erb
<h1>New crypto</h1>

<%= render "form", crypto: @crypto %>

<br>

<div>
  <%= link_to "Back to cryptos", cryptos_path %>
</div>

app/views/cryptos/show.html.erb
<div class="card" style="width: 18rem;">
  <div class="card-body">
    <h5 class="card-title"><%= @crypto.symbol.upcase %></h5>
  </div>

  <ul class="list-group list-group-flush">
    <li class="list-group-item">
      <strong>Buy Price: </strong> <%= @crypto.cost_per %>
    </li>
    <li class="list-group-item">
      <strong>Amount Owned: </strong> <%= @crypto.amount_owned %>
    </li>
  </ul>

  <div class="card-footer">
    <div class="row row-cols-lg-auto g-3 align-items-center">
    <%= link_to "Back", cryptos_path, class: 'btn btn-light btn-sm' %>
    <%= link_to "Edit", edit_crypto_path(@crypto), class: 'btn btn-light btn-sm' %>
    <%= button_to "Delete coin", @crypto, method: :delete, class: 'btn btn-outline-danger btn-sm' %>
    </div>
  </div>
</div>

app/views/home/about.html.erb
<h1>About Us</h1>
<p>My name is Andrey</p>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

<br/><br/>

<%# @coins %>

<% for x in @coins do %>
  <% if @my_coins.include? x['symbol'] %>
    <%= x['symbol'] %>: <%= x['symbol'] %>:
    <br/>
    <%= x['quote']['USD']['price'] %>
    <!--
      -->
      <pre style='white-space: pre-wrap;'><%= x %></pre>
  <% end %>
<% end %>

app/views/home/lookup.html.erb
<h3>Look Up A Single Crypto Currency</h3>

<%= form_tag home_lookup_path, :method => 'POST', data: {turbo: false} do %>
  <%= text_field_tag 'sym', nil, placeholder: 'Enter Crypto Symbol', size: 50 %>
  <%= submit_tag 'Lookup Stock Quote' %>
<% end %>



<% if @symbol && @info %>
<div>
<%= @symbol %>
<br/>
<%= @info['symbol'] %>: <%= @info['symbol'] %>:
<br/>
<%= @info['quote']['USD']['price'] %>
<!--
  -->
  <pre style='white-space: pre-wrap;'><%= @info %></pre>
</div>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-warning alert-dismissible">
    <button class="close">
      <i class="glyphicon glyphicon-remove-circle"></i>
    </button>
    <%= content_tag(:div, msg) %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container">
    <%= link_to "Crypto Portfolio", root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About Us", home_about_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Lookup", home_lookup_path, class: 'nav-link' %>
        </li>
      </ul>
      <!--
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
      -->
      <ul class="navbar-nav mb-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Your List", cryptos_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "Add New", new_crypto_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to "User Profile", edit_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= button_to "Log Out", destroy_user_session_path, class: 'nav-link', method: :delete %>
          </li>
        <% else %>
          <li class="nav-item pe-2">
            <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-outline-success' %>
          </li>
          <li class="nav-item">
            <%= link_to "Log In", new_user_session_path, class: 'btn btn-outline-primary' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crypto Currency Portfolio</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container mt-5">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
  </body>
</html>